# Generated by Django 4.2.4 on 2023-10-03 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="Date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="InvoiceCustomerName",
            new_name="invoice_customer_name",
        ),
    ]
